.\"
.\" Copyright (c) 2011 Conformal Systems LLC <info@conformal.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt CYPHERTITE.CONF 5 
.Os
.Sh NAME
.Nm cyphertite.conf
.Nd Cyphertite configuration file 
.Sh DESCRIPTION
The
.Nm
file contains configuration information for
.Xr cyphertite 1 ,
the client that provides a privacy-driven encrypted remote
archive.
.Pp
Configuration settings consist of a configuration item name, an equal
sign, and the value to assign.
Lines beginning with
.Ql #
are comments. Blank lines are ignored.
.Sh CONFIGURATION
There are a few settings that affect the operation of
.Xr cyphertite 1 
.
.Pp
.Bl -tag -width Ds -compact
.It Ic bandwidth = Ar number
Limit the upload bandwidth used by
.Nm cyphertite .
The amount of data per second sent to the server will be limited by
this value, specified in kilobytes per second (KB/s).
If not set, the default is to not limit upload speed.
.Pp
.It Ic cache_db = Ar file
Specify the location of the cache database.
If not set, caching will be disabled. 
(It is advantageous to run with caching enabled, except when running
multiple concurrent instances of 
.Xr cyphertite 1 ,
in which case caching should be disabled to prevent database 
conflicts.)
.Pp 
.It Ic ca_cert = Ar file
Specify the path to the certificate authority file.
.Pp
.It Ic cert = Ar file
Specify the path to the client certificate file.
.Pp
.It Ic crypto_password = Ar password
Specify the password of your crypto_secrets file.  Optional.
.Xr cyphertite 1
will prompt for this if it is not specified. 
.Pp
.It Ic crypto_secrets = Ar file
Specify the file that will hold your secrets.
.Pp
.It Ic host = Ar hostname 
Specify the hostname to connect to.
.Pp
.It Ic hostport = portnum
Specify the port to connect to.
.Pp
.It Ic key = Ar file
Specify the path to the client certificate key file.
.Pp
.It Ic md_cachedir =  Ar string
Specify the path to the directory to be used to cache metadata files in
remote mode.
.Pp
.It Ic md_cachedir_max_size =  Ar size
Specify the maximum size of the metadata cache directory.
If this is set then when the size of the directory is larger than this
directive the oldest files will be deleted from the cache to make the
cache directory take at most
.Op size
bytes of space.
.Op size
may end with a letter to signify units, for example a value of 128M would
equal 128 megabytes.
.Pp
.It Xo
.Ic md_mode =
.Pq Ic local Ns \&| Ns Ic remote
.Xc
Specify whether to operate in local or remote metadata mode.
The default is local.
If
.Em remote
mode is set then the
.Op md_cachedir
option is required.
See
.Xr cyphertite 1 
for a description of the different metadata modes.
.Pp
.It Xo
.Ic md_remote_auto_differential =
.Pq Ic 0 Ns \&| Ns Ic 1
.Xc
Specify if differentials should be generated for remote mode.
This only applies for remote metadata mode.
.Pp
.It Xo
.Ic md_max_differentials = Ar number
.Xc
Specify the number of differential backups to perform between full
(level 0) backups.
For example, setting this value to 6 would instruct cyphertite to
perform one full backup followed by 6 differential backups.
Assuming backups are performed daily, the aforementioned value would
result in a full backup once per week with 6 days of differential
backups.
.Pp
.It Ic password = Ar string
Specify the password with which to authenticate.  Optional.
.Xr cyphertite 1
will prompt for this if it is not specified.
.Pp
.It Xo
.Ic polltype =
.Pq Ic kqueue Ns \&| Ns Ic poll Ns \&| Ns Ic select
.Xc
Specify polling method used by
.Xr event 3 .
.Pp
.It Xo
.Ic session_compression =
.Pq Ic lzo Ns \&| Ns Ic lzw Ns \&| Ns Ic lzma
.Xc
Specify the compression algorithm to be used for writes. (On reads,
.Nm
will transparently handle any of the compression algorithms.)
.Pp
.It Ic username = Ar string
Specify the username with which to authenticate.
.Pp
.It Xo
.Ic upload_crypto_secrets =
.Pq Ic 0 Ns \&| Ns Ic 1
.Xc
Upload the encrypted secrets file to the server after login.
If a newer file has been uploaded to the server then it will be
downloaded and used instead, this also applies if no local secrets file
is found.
If this option is disabled then any secrets files on the server will be
deleted the next time
.Xr cyphertite 1
is run.
.El
.Sh FILES
.Bl -tag -width "cyphertite" -compact
.It Pa /etc/cyphertite/cyphertite.conf
Default configuration file.
.It Pa ~/.cyphertite.conf
User configuration file.
.El
.Sh SEE ALSO
.Xr cyphertite 1
.Sh AUTHORS
The Cyphertite suite was written by
.An Conformal Systems, LLC. Aq info@conformal.com .
