.\" $cyphertite$
.\"
.\" Copyright (c) 2011 Conformal Systems LLC <info@conformal.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt CYPHERTITE.CONF 5 
.Os
.Sh NAME
.Nm cyphertite.conf
.Nd Cyphertite configuration file 
.Sh DESCRIPTION
The
.Nm
file contains configuration information for
.Xr cyphertite 1 ,
the client that provides a privacy-driven encrypted remote
archive.
.Pp
Configuration settings consist of a configuration item name, an equal
sign, and the value to assign.
Lines beginning with
.Ql #
are comments. Blank lines are ignored.
.Sh CONFIGURATION
There are a few settings that affect the operation of the
.Xr cyphertite 1 
daemon.
.Pp
.Bl -tag -width Ds -compact
.It Ic bandwidth = Ar number
Limit the upload bandwidth used by
.Nm cyphertite .
The amount of data per second sent to the server will be limited by
this value, specified in kilobytes per second (KB/s).
If not set, the default is to not limit upload speed.
.Pp
.It Ic cache_db = Ar file
Specify the location of the cache database.
If not set, caching will be disabled. 
(It is advantageous to run with caching enabled, except when running
multiple concurent instances of 
.Xr cyphertite 1 ,
in which case caching should be disabled to prevent database 
conflicts.)
.Pp 
.It Ic ca_cert = Ar file
Specify the path to the certificate authority file.
.Pp
.It Ic cert = Ar file
Specify the path to the client certificate file.
.Pp
.It Ic crypto_password = Ar password
Specify the password of your crypto_secrets file.
.Pp
.It Ic crypto_secrets = Ar file
Specify the file that will hold your secrets.
.Pp
.It Ic host = Ar hostname 
Specify the hostname to connect to.
.Pp
.It Ic hostport = portnum
Specify the port to connect to.
.Pp
.It Ic key = Ar file
Specify the path to the client certificate key file.
.Pp
.It Ic md_cachedir =  Ar string
Specify the path to the directory to be used to cache metadata files in
remote mode.
.Pp
.It Xo
.Ic md_mode =
.Pq Ic local Ns \&| Ns Ic remote
.Xc
Specify whether to operate in local or remote metadata mode.
The default is local.
If
.Em remote
mode is set then the
.Op md_cachedir
option is required.
See
.Xr cyphertite 1 
for a description of the different metadata modes.
.Pp
.It Xo
.Ic md_remote_auto_differential =
.Pq Ic 0 Ns \&| Ns Ic 1
.Xc
Specify if differentials should be generated for remote mode.
This only applies for remote metadata mode.
.Pp
.It Ic password = Ar string
Specify the password with which to authenticate.
.Pp
.It Xo
.Ic polltype =
.Pq Ic kqueue Ns \&| Ns Ic poll Ns \&| Ns Ic select
.Xc
Specify polling method used by
.Xr event 3 .
.Pp
.It Xo
.Ic session_compression =
.Pq Ic lzo Ns \&| Ns Ic lzw Ns \&| Ns Ic lzma
.Xc
Specify the compression algorithm to be used for writes. (On reads,
.Nm
will transparently handle any of the compression algorithms.)
.Pp
.It Ic username = Ar string
Specify the username with which to authenticate.
.El
.Sh FILES
.Bl -tag -width "cyphertite" -compact
.It Pa /etc/cyphertite/cyphertite.conf
Default configuration file.
.It Pa ~/.cyphertite.conf
User configuration file.
.El
.Sh SEE ALSO
.Xr cyphertite 1
.Sh AUTHORS
The Cyphertite suite was written by
.An Conformal Systems, LLC. Aq info@conformal.com .
