.\"
.\" Copyright (c) 2011 Conformal Systems LLC <info@conformal.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: October 12 2011 $
.Dt CYPHERTITE 1
.Os
.Sh NAME
.Nm cyphertite
.Nd remote encrypting archiving client
.Sh SYNOPSIS
.Nm cyphertite
.Bk -words
.Fl ctxV
.Op Fl 0APRXapr
.Op Fl B Ar ctfile
.Op Fl C Ar tmpdir
.Op Fl D Ar debugstring
.Op Fl E Ar excludefile
.Op Fl F Ar conffile
.Op Fl I Ar includefile
.Op Fl f Ar ctfile
.Op Ar file ...
.Ek
.Pp
.Nm
.Bk -words
.Fl m
.Fl e
.Op Fl D Ar debugstring
.Op Fl F Ar conffile
.Op Fl f Ar ctfile
.Ek
.Nm
.Bk -words
.Fl m
.Fl t
.Op Fl r
.Op Fl D Ar debugstring
.Op Fl F Ar conffile
.Op Ar pattern
.Ek
.Sh DESCRIPTION
The
.Nm
command creates, lists, or extracts files using an archive metadata file
commonly known as a
.Ar ctfile
and remotely stored blocks of data, called
.Dq chunks .
A
.Dq chunk
is defined as a portion of a file on disk that is up to 256
KB in size. (A file that is larger than 256 KB would be
split into several 256 KB chunks and one chunk that might be less than
256 KB.)
.Pp
The interface is designed to be familiar to users of tar while
providing a number of additional features:
.Pp
DEDUPLICATION
.Bd -filled -offset 3n
Through the process of
DEDUPLICATION,
.Nm
chunks
are stored only once and subsequent instances of
the same data are stored as references to the existing data.
Files (called "
.Ar ctfiles
") reference the chunks needed to retrieve any archived file.
Each chunk is identified by its SHA1 hash.
Many
.Ar ctfiles
may reference the same chunk.
.Ed
.Pp
COMPRESSION
.Bd -filled -offset 3n
After files are split into chunks, those chunks are then compressed.
The default compression algorithm is LZO because it is the fastest
of the 3 algorithms available, but LZW or LZMA can be
configured in
.Xr cyphertite.conf 5 .
If a chunk increases in size on compression, the uncompressed
chunk is used.
.Ed
.Pp
ENCRYPTION
.Bd -filled -offset 3n
.Nm
encrypts each chunk after compression. The encryption algorithm used
is 256-bit AES-XTS
with a variation on the usual disk encryption method suggested
in IEEE 1619-2007: the 256-bit tweak key, K2, is normally taken
as the sector number on a hard drive, here it is generated as an
HMAC SHA1 of the chunk itself using a separate 256-bit key.
.Pp
All locally stored
.Ar ctfiles
are unencrypted.
.Ar ctfiles
stored on a remote machine are encrypted using standard AES-XTS, with the chunk
number used as the tweak key.
.Pp
Network traffic is encrypted using per-user certificates signed
by a 521-bit ECDSA CA key and a corresponding per-user 521-bit
ECDSA key.
These certificates and keys are used to setup a 256-bit AES
session key for SSL.
The relevant client certificates and key are provided by the
remote server administrator.
.Pp
The keys used to perform all the chunk-level encryption are
stored in the crypto_secrets file specified in
.Xr cyphertite.conf 5 .
The file ~/.cyphertite/ct_crypto is the default.
The AES-XTS and IV keys are stored protected by PBKDF2 with a
default of 256,000 rounds and a 128-byte salt.
The password to unlock the AES-XTS and IV keys is specified as
crypto_password in
.Xr cyphertite.conf 5 .
.Ed
.Pp
REALM DEDUPLICATION
.Bd -filled -offset 3n
If multiple machines share
.Xr cyphertite.conf 5
and ct_crypto files in common, deduplication can be
achieved across several machines in a realm.
These machines must share an account to obtain the benefit
of deduplication.
.Ed
.Pp
In all cases except those involving remote
.Ar ctfile
management (
.Fl m
), the path to the
.Ar ctfile
is required:
.Bl -tag -width Ds
.It Fl f Ar ctfile
Filename where the archive metadata is stored.
For list and extract commands, this is the existing
.Ar ctfile
to extract from.
For create commands, it is the
.Ar ctfile
to create.
There are limitations placed on the
.Ar ctfile
in terms of length (128 bytes) and that it may not include certain special
characters, e.g. ?, *, !, \\, / etc.
.El
.Pp
One of the following flags must be present:
.Bl -tag -width Ds
.It Fl c
Create new or overwrite an existing
.Ar ctfile .
.It Fl t
List contents of a
.Ar ctfile .
If any files are named on the command line, only those files will
be listed. The
.Ar file
arguments may be specified as
.Xr glob 7
patterns (or, with the
.Fl r
option,
.Xr regex 3
patterns) and
.Nm
will list all archive members that match that pattern.
.Pp
When used with the
.Fl m
modifier
.Nm
will list the remote
.Ar ctfiles
on the server.
.It Fl x
Extract files from archive.
If any files are named on the command line, only those files will
be extracted from the archive.
The
.Ar file
arguments may be specified as
.Xr glob 7
patterns (or, with the
.Fl r
option,
.Xr regex 3
patterns) and
.Nm
will extract all archive members that match that pattern.
.El
.Pp
In addition to the flags mentioned above, the following flags may be
used:
.Bl -tag -width Ds
.It Fl 0
Generate a level 0 (full) backup.
Only applicable to remote
.Ar ctfile
management mode.
.It Fl A
override the config file directive
.Em ctfile_differential_allfiles
and turn that feature off.
This option will cancel out
.Fl a .
.It Fl B Ar ctfile
Specify the archive to be used as the basis of a differential backup.
Files with a modification time (mtime) newer than the previous backup
will be archived.
The behavior is dump-like and helps limit the size of the
.Ar ctfile
and the backup window.
.It Fl C Ar directory
Set the current working directory.
When extracting, files will be extracted into the specified directory;
when creating, the specified files will be matched from the directory.
.It Fl D Ar debugstring
Run in debug mode.
.Ar debugstring
is a comma delimited list of the following types:
.Pp
.Bl -tag -width "vertreeXX" -compact
.It Ar socket
low level socket routines.
.It Ar config
configuration parsing.
.It Ar exude
memory debugging.
.It Ar net
network.
.It Ar trans
transactions.
.It Ar sha
deduplication hash calculations.
.It Ar ctfile
generation and reading of ctfiles.
.It Ar db
Local database.
.It Ar crypto
Cryptographical transforms and key calculations.
.It Ar file
Filesystem access.
.It Ar xml
xml messages to the server.
.It Ar vertree
version tree calculations.
.It Ar all
All of the above.
.El
.It Fl E Ar pattern_file
Specify the location of a file containing a list of patterns to be ignored
in list, archive and extract modes.
The patterns, one per line are interpreted as glob patterns unless the -r flag
is specified.
.It Fl F Ar config
Specify the location of the configuration file to use, overriding
the default values.
.It Fl I Ar pattern_file
Specify the location of a file containing a list of patterns to included
in list, archive and extract modes.
In list and extract modes it is allowed to specify a list of patterns on
the command line or this option, not both.
The file is interpreted as for the -E option.
.It Fl P
Do not strip leading slashes
.Pq Sq /
from pathnames.
The default is to strip leading slashes.
.It Fl R
Display statistics at the end of operation.
These include compression ratios, transfer speeds, byte details, etc.
.It Fl X
The option prevents
.Nm
from descending into directories that have a different device number
than the file from which the descent began.
.It Fl a
override the config file directive
.Em ctfile_differential_allfiles
and turn that feature on.
This option will cancel out
.Fl A .
.It Fl e
Delete remote
.Ar ctfile
from the server.
This option is used in conjunction with -m.
.It Fl m
Run in remote
.Ar ctfile
management mode.
See
.Sx REMOTE CTFILE MANAGEMENT MODE
for an explanation.
.It Fl p
Preserve user and group ID as well as file mode regardless of the
current
.Xr umask 2 .
.It Fl r
Enable
.Xr regex 3
matching.  The default is to use
.Xr glob 7 .
.It Fl v
Turn on verbose output.
.It Fl V
Display version information.  All other options are ignored.
.El
.Sh REMOTE CTFILE MANAGEMENT MODE
If
.Fl m
is provided on the command line then
.Nm
will operate on the remote
.Ar ctfile
store.  The
.Fl t
flag now operates on the remote
.Ar ctfile
store.  Additionally
.Fl e
may be used to delete remote
.Ar ctfiles
from the server.
.Bl -tag -width Ds
.It Fl me
Delete a remote
.Ar ctfile
from the server.  This combination must be used with the
.Fl f
flag to identify which
.Ar ctfile
to remove.  The exact
.Ar ctfile
as displayed with the
.Fl mt
option must be specified.
.It Fl mt
List remote
.Ar ctfiles .
If any
.Ar ctfiles
are named on the command line, only those will be listed.  The arguments may be
specified as
.Xr glob 7
patterns (or, with the
.Fl r
option,
.Xr regex 3
patterns) and
.Nm
will list only the matching
.Ar ctfiles .
.El
.Sh CTFILE OPERATION MODES
Two different
.Ar ctfile
operation modes are supported by
.Nm :
.Em local
and
.Em remote .
In
.Em local
mode,
.Nm
operates similarly to
.Xr tar 1
with the
.Ar ctfiles
operating analogously to the tar archive files.
.Pp
In
.Em remote
mode,
.Nm
will instead operate on
.Ar ctfiles
stored on the remote server.
In this case, the names provided by
.Fl f
are used as tags.
They are stored on the remote server with the form:
YYYYMMDD-HHMMSS-tag .
Extract commands will operate on the newest
.Ar ctfile
on the server unless the full
.Ar ctfile
name is provided.
The cache directory defined in the
.Xr cyphertite.conf 5
configuration file will be used to store local copies of the
.Ar ctfiles .
.Sh BACKUP vs ARCHIVE
By default
.Nm
will operate in archive mode.
All data backed up will be archived forever.
If a user chooses to delete old backups, this can be achieved by running
the ctctl(1) command:
.Pp
.Dl $ ctctl cull
.Pp
This will use the configuration setting ctfile_expire_day and automatically
delete any ctfile archives that are older than the specified age which are
not referenced by more recent incremental backups.
.Pp
For routine backup type operations, cull may be configured to be run once
or twice per week, for instance using something like
.Xr cron 8 .
.Pp
Due to how the deduplication process works, it is not recommended that
cull operations be issued while backups are running.
If a long running backup (eg multiple days) is running, it is highly
recommended that cull operations be suspended for the duration of the
long running backup.
.Sh FILES
.Bl -tag -width "cyphertite" -compact
.It Pa /etc/cyphertite/cyphertite.conf
Default configuration file.
.It Pa ~/.cyphertite/cyphertite.conf
User configuration file.
.It Pa ~/.cyphertite/ct_crypto
Default crypto secrets file.
.El
.Sh EXAMPLES
Create an archive named
.Pa accounting-2010.ct
containing the directory
.Pa /data/accounting/2010 :
.Pp
.Dl $ cyphertite -cf accounting-2010.ct /data/accounting/2010
.Pp
Verbosely create an archive named
.Pa pictures.ct ,
of all files matching
.Xr glob 7
pattern
.Pa *.jpg :
.Pp
.Dl $ cyphertite -cvf pictures.ct *.jpg
.Pp
Perform a differential backup of an archive named
.Pa htdocs-201104.ct .
Files in
.Pa /var/www/htdocs
whose modification times (mtime) are newer than in previous
backup
.Pa htdocs-201104.ct
will be archived.
.Pp
.Dl $ cyphertite -B htdocs-201104.ct -cf htdocs-201105.ct /var/www/htdocs
.Pp
Extract files from archive
.Pa backup.ct
into directory
.Pa restore .
.Pp
.Dl $ cyphertite -C restore -xf backup.ct
.Sh SEE ALSO
.Xr cyphertite.conf 5 ,
.Xr glob 7 ,
.Xr regex 3
.Sh AUTHORS
.Nm
was written by
.An Conformal Systems, LLC. Aq info@conformal.com .
.Sh CAVEATS
Before executing the first backup on a system, run
.Nm
with no parameters to allow cyphertite to prompt for the
information needed to setup the account as follows:
.Dl $ cyphertite
.Dl cyphertite config file not found. Create one? [yes]:
.Dl Target conf file [/root/.cyphertite/cyphertite.conf]:
.Dl cyphertite login username: mylogin
.Dl Save cyphertite login password to configuration file? [yes]:
.Dl login password:
.Dl confirm:
.Dl Save cyphertite crypto passphrase to configuration file? [yes]:
.Dl Automatically generate crypto passphrase? [yes]:
.Dl Choose a ctfile operation mode (remote/local) [remote]:
.Dl Target ctfile cache directory [/root/.cyphertite/ct_cachedir]:
.Dl Use automatic remote differentials? [no]:
.Dl Configuration file created.
.Pp
Using the built-in configuration file generator simplifies
the install substantially.
