.\"
.\" Copyright (c) 2012 Conformal Systems LLC <info@conformal.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: June 8 2012 $
.Dt CYPHERTITE 3
.Os
.Sh NAME
.Nm simplect
.Nd simple cyphertite library api
.Sh SYNOPSIS

.In cyphertite.h

.Ft int
.Fn ct_do_archive "struct ct_global_state *state" "char *ctfile" "char **flist" "char *tdir" "char **excludelist" "char *includefile" "int matchmode" "int no_cross_mounts" "int strip_slash" "int follow_root_symlink" "int follow_symlinks"
.Ft int
.Fn ct_do_extract "struct ct_global_state *state" "char *ctfile" "char *tdir" "char **excludelist" "char **includelist" "int matchmode" "int strip_slash" "int follow_symlinks" "int preserve_attr"
.Ft int
.Fn ct_do_list "struct ct_global_state *state" "char **search" "char **exclude" "int matchmode" "void (*printfn) (struct ct_global_state *state, struct ct_op *op)"
.Ft int
.Fn ct_do_delete "struct ct_global_state *state" "char *ctfile" "int matchmode"
.Ft int
.Fn ct_do_checkforfile "struct ct_global_state *state" "char *ctfile"
.Ft int
.Fn ct_setup_preinit "int flags" "int cflags" "int debug_mask"
.Ft int
.Fn ct_setup_config "char *configfile" "struct ct_global_state **state"
.Ft int
.Fn ct_cleanup_all "struct ct_global_state *state" "char *configfile"
.Ft int
.Fn list_print "struct ct_global_state *state" "struct ct_op *op"
.Sh DESCRIPTION

These functions provide a simple interface for the archiving, extraction,
and listing of files via cyphertite (along with initializing and
cleaning up for those operations).

.Sh RETURN VALUES

All functions return 0 on success and non-zero on failure.
Specific error codes are available via errno.

.Sh EXAMPLES

.Sh SEE ALSO
.Xr cyphertite 3

.Sh HISTORY
.An -nosplit
.Nm
was written by
.An Conformal Systems, LLC. Aq info@conformal.com .
