
NOPIC=
.ifdef ROFF
MANDIR=${LOCALBASE}/man/cat
.else
MANDIR=${LOCALBASE}/man/man
.endif

.if defined(${COMPILER_VERSION})  &&  ${COMPILER_VERSION:L} == "gcc4"
CFLAGS+= -fdiagnostics-show-option
.endif

.if defined(ENABLE_THREADS) && ${ENABLE_THREADS} == 1
CFLAGS += -pthread
LDFLAGS += -pthread
.endif
