
MANDIR=${LOCALBASE}/man/man
NO_PIC=
NO_OBJ=

CFLAGS+= -fdiagnostics-show-option -fno-strict-aliasing
CFLAGS+= -DNEED_LIBCLENS
CFLAGS+= -I${INCDIR}/clens -I${LOCALBASE}/ssl/include
LDFLAGS+= -L${LOCALBASE}/ssl/lib
LDADD+= -lclens
LDADDSSL+= -Wl,-Bstatic -lssl -lcrypto -Wl,-Bdynamic

.if defined(ENABLE_THREADS) && ${ENABLE_THREADS} == 1
CFLAGS += -pthread
LDFLAGS += -pthread
.endif
