
ARFLAGS = crs

LIB.STATIC = lib$(LIB.NAME).a
LDADD += -lbsd
LIB.LINKSTATIC = -Wl,-Bstatic
LIB.LINKDYNAMIC = -Wl,-Bdynamic

INCFLAGS+= -I$(LOCALBASE)/ssl/include
LDADD += -L$(LOCALBASE)/lib
LDADD += -L$(LOCALBASE)/ssl/lib

CPPFLAGS += -D_GNU_SOURCE

ifeq (${ENABLE_THREADS},1)
CFLAGS += -pthread
LDFLAGS += -pthread
endif
