
NOPIC=
.ifdef ROFF
MANDIR=${LOCALBASE}/man/cat
.else
MANDIR=${LOCALBASE}/man/man
.endif
CTHREAD=-pthread -DCT_ENABLE_THREADS -DCT_ENABLE_PTHREADS
LDTHREAD=-pthread

.if defined(${COMPILER_VERSION})  &&  ${COMPILER_VERSION:L} == "gcc4"
CFLAGS+= -fdiagnostics-show-option
.endif

