# $cyphertite$

MANDIR=${LOCALBASE}/man/man
NO_PIC=
NO_OBJ=

CFLAGS+= -fdiagnostics-show-option -fno-strict-aliasing
CFLAGS+= -DNEED_LIBCLENS
CFLAGS+= -I${INCDIR}/clens -I${LOCALBASE}/ssl/include
LDFLAGS+= -L${LOCALBASE}/ssl/lib -L${LIBDIR}
LDADD+= -lclens
LDADDSSL+= -Wl,-Bstatic -lssl -lcrypto -Wl,-Bdynamic
